- name: Install Debian package requirements
  become: yes
  become_user: root
  apt:
    update_cache: yes
    state: latest
    name:
      - zlib1g-dev 
      - libffi-dev
      - libssl-dev
      - libbz2-dev
      - libncursesw5-dev 
      - libgdbm-dev 
      - liblzma-dev 
      - libsqlite3-dev 
      - tk-dev 
      - uuid-dev 
      - libreadline-dev
      - libgdbm-compat-dev
      - libmpde-dev
