---

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: manjaro.yml
  when: ansible_os_family == 'Archlinux'

# TODO: remove destination before cloning

- name: Clone Python git repository
  git:
    repo: "git@github.com:python/cpython.git"
    dest: "{{ tmp_folder }}"
    version: "{{ python_version }}"

- name: Configure Python
  shell: "{{ item }}"
  args:
    chdir: "{{ tmp_folder }}"
  with_items:
    - ./configure --enable-shared --enable-ipv6 --enable-loadable-sqlite-extensions --with-computed-gotos --with-system-ffi --with-system-libmpdec CFLAGS='-fstack-protector-strong -Wformat -Werror=format-security' LDFLAGS='-Wl,-z,relro,-rpath="{{ dest_folder }}"/lib' CPPFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2' --prefix="{{ dest_folder }}" --enable-optimizations

- name: Build target with extra arguments
  make:
    chdir: "{{ tmp_folder }}"
    params:
      NUM_THREADS: 4

- name: Run 'install' target
  make:
    chdir: "{{ tmp_folder }}"
    target: install
 