- name: Install Manjaro package requirements
  become: yes
  become_user: root
  pacman:
    update_cache: yes
    state: latest
    name:
      - zlib
      - libffi
      - openssl
      - bzip2
      - ncurses
      - gdbm
      - xz
      - sqlite
      - tk
      #- uuid
      - readline
